version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: txwatch_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_watchdog
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/

volumes:
  pg_data:
